-- Redbridge Exam Platform — Supabase/PostgreSQL schema
create extension if not exists pgcrypto;

create table if not exists organisations (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);
create table if not exists settings (
  org_id bigint not null references organisations(id) on delete cascade,
  key text not null,
  value jsonb not null,
  primary key (org_id,key)
);
create table if not exists academic_years (
  id bigint generated by default as identity primary key,
  org_id bigint not null references organisations(id) on delete cascade,
  label text not null,
  is_current boolean not null default false
);
create table if not exists users (
  id bigint generated by default as identity primary key,
  org_id bigint not null references organisations(id) on delete cascade,
  email text not null unique,
  password_hash text not null,
  first_name text not null,
  last_name text not null,
  role text not null check (role in ('student','teacher','academic_admin','super_admin')),
  status text not null check (status in ('pending','active','rejected','disabled')),
  must_change_password boolean not null default false,
  failed_logins integer not null default 0,
  locked_until timestamptz,
  created_at timestamptz not null default now(),
  last_login timestamptz
);
create table if not exists role_permissions (
  role text not null,
  permission text not null,
  primary key(role,permission)
);
create table if not exists sessions (
  token_hash text primary key,
  user_id bigint not null references users(id) on delete cascade,
  csrf text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  ip text,
  ua text
);
create index if not exists idx_sessions_exp on sessions(expires_at);

create table if not exists classes (
  id bigint generated by default as identity primary key,
  org_id bigint not null references organisations(id) on delete cascade,
  academic_year_id bigint not null references academic_years(id) on delete cascade,
  name text not null,
  grade integer not null check (grade between 1 and 11),
  class_teacher_id bigint references users(id),
  unique(org_id,academic_year_id,name)
);
create table if not exists student_profiles (
  user_id bigint primary key references users(id) on delete cascade,
  student_number text,
  date_of_birth date,
  guardian_email text,
  requested_grade integer,
  requested_class_id bigint references classes(id)
);
create table if not exists student_enrolments (
  id bigint generated by default as identity primary key,
  student_id bigint not null references users(id) on delete cascade,
  class_id bigint not null references classes(id) on delete cascade,
  academic_year_id bigint not null references academic_years(id) on delete cascade,
  unique(student_id,academic_year_id)
);
create table if not exists subjects (
  id bigint generated by default as identity primary key,
  org_id bigint not null references organisations(id) on delete cascade,
  name text not null,
  unique(org_id,name)
);
create table if not exists teaching_assignments (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references users(id) on delete cascade,
  class_id bigint not null references classes(id) on delete cascade,
  subject_id bigint not null references subjects(id) on delete cascade,
  unique(teacher_id,class_id,subject_id)
);

create table if not exists questions (
  id bigint generated by default as identity primary key,
  org_id bigint not null references organisations(id) on delete cascade,
  subject_id bigint not null references subjects(id),
  grade integer not null check (grade between 1 and 11),
  topic text not null default '',
  subtopic text not null default '',
  difficulty text not null check (difficulty in ('easy','medium','hard','olympiad')),
  type text not null check (type in ('mcq','truefalse','multi','short','numeric')),
  language text not null default 'en' check (language in ('en','ru','uz')),
  text text not null,
  options_json jsonb,
  correct_json jsonb not null,
  marks numeric(10,2) not null default 1,
  negative_marks numeric(10,2) not null default 0,
  explanation text not null default '',
  author_id bigint not null references users(id),
  version integer not null default 1,
  status text not null default 'active' check (status in ('active','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_questions_find on questions(org_id,subject_id,grade,difficulty,status);

create table if not exists exams (
  id bigint generated by default as identity primary key,
  org_id bigint not null references organisations(id) on delete cascade,
  title text not null,
  subject_id bigint not null references subjects(id),
  grade integer not null check (grade between 1 and 11),
  exam_type text not null,
  language text not null default 'en' check (language in ('en','ru','uz')),
  description text not null default '',
  instructions text not null default '',
  duration_min integer not null,
  pass_percent numeric(6,2) not null default 50,
  attempts_allowed integer not null default 1,
  randomise_questions boolean not null default true,
  randomise_options boolean not null default true,
  allow_review_after boolean not null default true,
  start_time timestamptz,
  end_time timestamptz,
  status text not null default 'draft' check (status in ('draft','scheduled','closed')),
  results_published boolean not null default false,
  created_by bigint not null references users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists exam_questions (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references exams(id) on delete cascade,
  position integer not null,
  source_question_id bigint,
  source_version integer,
  topic text not null default '',
  snapshot_json jsonb not null
);
create table if not exists exam_assignments (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references exams(id) on delete cascade,
  class_id bigint references classes(id) on delete cascade,
  student_id bigint references users(id) on delete cascade,
  check ((class_id is null) <> (student_id is null))
);
create index if not exists idx_exam_assignments_exam on exam_assignments(exam_id);

create table if not exists attempts (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references exams(id) on delete cascade,
  student_id bigint not null references users(id) on delete cascade,
  attempt_no integer not null,
  status text not null check (status in ('IN_PROGRESS','MARKED','CANCELLED')),
  started_at timestamptz not null,
  deadline_at timestamptz not null,
  submitted_at timestamptz,
  submit_reason text,
  order_json jsonb not null,
  score numeric(10,2), total numeric(10,2), percentage numeric(7,2), passed boolean, grade_label text,
  ip text,
  unique(exam_id,student_id,attempt_no)
);
create index if not exists idx_attempts_exam_student on attempts(exam_id,student_id);

create table if not exists answers (
  attempt_id bigint not null references attempts(id) on delete cascade,
  exam_question_id bigint not null references exam_questions(id) on delete cascade,
  answer_json jsonb,
  is_correct boolean,
  marks_awarded numeric(10,2),
  answered_at timestamptz not null default now(),
  primary key(attempt_id,exam_question_id)
);
create table if not exists integrity_events (
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references attempts(id) on delete cascade,
  at timestamptz not null default now(),
  kind text not null
);
create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  org_id bigint,
  at timestamptz not null default now(),
  user_id bigint,
  user_label text,
  action text not null,
  entity text,
  entity_id text,
  detail jsonb,
  ip text
);
create index if not exists idx_audit_at on audit_logs(at desc);

create table if not exists pilot_requests (
  id bigint generated by default as identity primary key,
  ref text not null unique,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  message text not null,
  status text not null default 'new' check(status in ('new','read','replied'))
);

alter table organisations enable row level security;
alter table settings enable row level security;
alter table academic_years enable row level security;
alter table users enable row level security;
alter table sessions enable row level security;
alter table classes enable row level security;
alter table student_profiles enable row level security;
alter table student_enrolments enable row level security;
alter table subjects enable row level security;
alter table teaching_assignments enable row level security;
alter table questions enable row level security;
alter table exams enable row level security;
alter table exam_questions enable row level security;
alter table exam_assignments enable row level security;
alter table attempts enable row level security;
alter table answers enable row level security;
alter table integrity_events enable row level security;
alter table audit_logs enable row level security;
alter table pilot_requests enable row level security;
